# Generated by Django 3.1.4 on 2021-01-01 19:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('vin_code', models.CharField(max_length=30, unique=True, verbose_name='vin code')),
                ('token', models.CharField(max_length=30, unique=True, verbose_name='token')),
            ],
        ),
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='BikeCurrentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('load', models.BooleanField(default=False)),
                ('valide', models.BooleanField(default=True)),
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bike', verbose_name='bike')),
            ],
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CashInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Инвайт код')),
                ('cash', models.IntegerField(verbose_name='Токены')),
                ('expired', models.BooleanField(default=False, verbose_name='Использован')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_rent_start', models.DateTimeField(auto_now_add=True, verbose_name='datetime rent start')),
                ('end', models.BooleanField(default=False)),
                ('datetime_rent_end', models.DateTimeField(blank=True, verbose_name='datetime rent end')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bikecurrentlocation', verbose_name='bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0)),
                ('start_point_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='start point location')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BikeReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bike', verbose_name='bike')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bikebrand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bikemodel', verbose_name='model'),
        ),
        migrations.CreateModel(
            name='UserBikeLocation',
            fields=[
                ('userlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userlocation')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bike', verbose_name='bike')),
            ],
            bases=('core.userlocation',),
        ),
    ]
