# Generated by Django 3.1.4 on 2021-01-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210101_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_location', to='core.bikecurrentlocation', verbose_name='bike'),
        ),
    ]
