# Generated by Django 3.1.4 on 2021-01-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210104_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='datetime_paid',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime paid'),
        ),
    ]
